### ISSUE TITLE
AttributeError: 'PgzipFile' object has no attribute '_buffer'

### ISSUE THREAD

**Issue by skinkie** [mgzip/mgzip#38]
```
Traceback (most recent call last):
  File "/home/skinkie/Sources/reference/gtfs-netex-test/db-to-xml.py", line 199, in <module>
    with pgzip.open('netex-output/huge.xml.gz', 'wt', thread=8, blocksize=2*10**8) as out:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skinkie/Sources/reference/gtfs-netex-test/.venv312/lib/python3.12/site-packages/pgzip/pgzip.py", line 85, in open
    return io.TextIOWrapper(binary_file, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gzip.py", line 256, in tell
    self._buffer.flush()
    ^^^^^^^^^^^^
AttributeError: 'PgzipFile' object has no attribute '_buffer'
```

**Comment by patrizok** [comment]
pgzip does not work with python 3.12, and problem is a bit about python core, so I couldn't fix.
@timhughes looking for maintainers, I hope we can find someone to fix problem.

**Comment by igregore-cst** [comment]
Just to say that I am also hoping for a solution.

**Comment by Hendricks27** [comment]
Same here. I am looking for a solution...

**Comment by timhughes** [comment]
Fixed: https://github.com/pgzip/pgzip/pull/42
https://github.com/pgzip/pgzip/releases/tag/v0.4.0
