### ISSUE TITLE
python3.12 AttributeError: 'zlib._ZlibDecompressor' object has no attribute 'unconsumed_tail'

### ISSUE THREAD

**Issue by timhughes** [mgzip/mgzip#33]
Issue in python3.12

Python version

    ❯ python3.12 --version
    Python 3.12.0b4

Error

                uncompress = self._decompressor.decompress(buf, size)
    >           if self._decompressor.unconsumed_tail != b"":
    E           AttributeError: 'zlib._ZlibDecompressor' object has no attribute 'unconsumed_tail'
    
    pgzip/pgzip.py:721: AttributeError

**Comment by jamadden** [comment]
FWIW, I got the original ``mgzip`` code working on Python 3.12 with this patch, in case its helpful for others running into this issue. 

When I say "working" I mean my test cases that de/compress data are passing. There may be corner cases I haven't run into yet. 

```python
try:
    from zlib import _ZlibDecompressor
except ImportError:
    # Python <= 3.11
    pass
else:
    # Python >= 3.12
    #
    # This version has changed from internally using
    # ``zlib.decompressobj`` to using the new
    # ``zlib._ZlibDecompressor`` class, which has almost, but not
    # quite, the same API. We:
    # - implement an API compatible version of _ZlibDecompressor;
    # - patch __init__ to use this instead of the original.

    # pylint:disable=protected-access

    # We are not allowed to use _ZlibDecompressor as a base class,
    # so we have to proxy to it. This slows us down some.
    class _MgzipDecompressor:
        unconsumed_tail = b''

        def __init__(self, *args, **kwargs):
            self.__backing = _ZlibDecompressor(*args, **kwargs)

        def __getattr__(self, name):
            return getattr(self.__backing, name)

    _orig_init = mgzip.multiProcGzip._MulitGzipReader.__init__
    def _mgzip_init_(self, *args, **kwargs):
        _orig_init(self, *args, **kwargs)
        assert self._decomp_factory is _ZlibDecompressor
        self._decomp_factory = _MgzipDecompressor
        self._decompressor = self._decomp_factory(**self._decomp_args)
    mgzip.multiProcGzip._MulitGzipReader.__init__ = _mgzip_init_

    # This method has been inlined in 3.12. It is only called from the end
    # of read()
    if not hasattr(mgzip.multiProcGzip._MulitGzipReader, '_add_read_data'):
        import zlib
        def _add_read_data(self, data):
            self._crc = zlib.crc32(data, self._crc)
            self._stream_size += len(data)
        mgzip.multiProcGzip._MulitGzipReader._add_read_data = _add_read_data

def _mgzip_read_exact(self, n):
    # Taken from Python 3.10. Their comment:
    #
    # Read exactly *n* bytes from `self._fp`
    # This method is required because self._fp may be unbuffered,
    # i.e. return short reads.
    #
    # mgzip relies on this internally right now, and so doesn't
    # work with 3.11 or 3.12. We patch it in.
    # pylint:disable=protected-access
    data = self._fp.read(n)
    while len(data) < n:
        b = self._fp.read(n - len(data))
        if not b:
            raise EOFError("Compressed file ended before the "
                           "end-of-stream marker was reached")
        data += b
    return data

if not hasattr(
    # Note typo.
    # pylint:disable-next=protected-access
    mgzip.multiProcGzip._MulitGzipReader,
    '_read_exact'
):
    # pylint:disable-next=protected-access
    mgzip.multiProcGzip._MulitGzipReader._read_exact = _mgzip_read_exact

**Comment by timhughes** [comment]
See #37

**Comment by patrizok** [comment]
@jamadden Can you please fix this problem for pgzip.

**Comment by timhughes** [comment]
Fixed: https://github.com/pgzip/pgzip/pull/42
https://github.com/pgzip/pgzip/releases/tag/v0.4.0
